#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'arxutils'
require "chbk"

dbconfig = Arxutils::Dbutil::DBCONFIG_MYSQL
dbconfig = Arxutils::Dbutil::DBCONFIG_SQLITE3

hs = {
  "db_dir" => Arxutils::Dbutil::DB_DIR,
  "migrate_dir" => Arxutils::Dbutil::MIGRATE_DIR,
  "config_dir" => Arxutils::Dbutil::CONFIG_DIR,
  "dbconfig" => dbconfig,
  "log_fname" => Arxutils::Dbutil::DATABASELOG,
}

infname = ARGV[0]
pn = Pathname.new( infname )
basename = pn.basename(".*")
dirname = pn.dirname
ext = pn.extname
category_pn =  dirname + Pathname.new( basename.to_s + "_category" + ext.to_s )
chbk = Chbk::Chbk.new(
                      :db,
                      hs,
                      )
#chbk.connect

def category_op(chbk, category_pn)
  chbk.load_category_file( category_pn )
#  count = chbk.category_count
#  chbk.list_category
#  puts count
#chbk.list_category
#  category = chbk.get_latest_category
#puts category.add_date
#  p category
#  chbk.list_category
#  puts chbk.max_add_date
end

def bookmark_op(chbk, pn)
  chbk.load_bookmark_file( pn )
  chbk.pickup_multiple_bookmarks
=begin
  bminfo = chbk.get_latest_bookmark
  p bminfo
  chbk.list_bookmark
  puts chbk.max_add_date
=end
end

bookmark_op(chbk, pn)
category_op(chbk, category_pn)


