#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'arxutils'
require "chbk"

start_time = Time.now

dbname = 'chbk'
db_dir = File.join( Arxutils::Dbutil::DB_DIR , dbname )
config_dir = File.join( Arxutils::Dbutil::CONFIG_DIR , dbname )
dbconfig = { :kind => Arxutils::Dbutil::DBCONFIG_MYSQL , :dbname => dbname , :db_dir => db_dir }
dbconfig = { :kind => Arxutils::Dbutil::DBCONFIG_SQLITE3 , :db_dir => db_dir }

hs = {
  "migrate_dir" => Arxutils::Dbutil::MIGRATE_DIR,
  "config_dir" => config_dir,
  "dbconfig" => dbconfig,
  "log_fname" => Arxutils::Dbutil::DATABASELOG,
}

infname = ARGV[0]
pn = Pathname.new( infname )
basename = pn.basename(".*")
dirname = pn.dirname
ext = pn.extname
category_pn =  dirname + Pathname.new( basename.to_s + "_category" + ext.to_s )
chbk = Chbk::Chbk.new(
                      :db,
                      hs,
                      )
#chbk.connect

def init(chbk , category_pn, pn )
  chbk.load_category_file( category_pn )
  chbk.load_bookmark_file( pn )
end

def category_op(chbk, category_pn)
#  count = chbk.category_count
#  chbk.list_category
#  puts count
#chbk.list_category
#  category = chbk.get_latest_category
#puts category.add_date
#  p category
  chbk.list_category
#  puts chbk.max_add_date
end

def bookmark_op(chbk, pn)
#  chbk.pickup_multiple_bookmarks_by_add_date
#  chbk.pickup_multiple_bookmarks_by_url
  bminfo = chbk.get_latest_bookmark
  chbk.list_bookmark
end

init(chbk, category_pn , pn )
bookmark_op(chbk, pn)
category_op(chbk, category_pn)
#chbk.pickup_multiple_bookmarks_between_gitmarks_and_other
=begin
chbk.pickup_not_sutable_bookmarks_for_folder.map{|x|
  puts [x.category , x.name, x.url].join("|")
}
=end
chbk.ensure_invalid
chbk.ensure_management
