#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'arxutils'
require "chbk/chbk"

start_time = Time.now

dbconfig = Arxutils::Dbutil::DBCONFIG_MYSQL
dbconfig = Arxutils::Dbutil::DBCONFIG_SQLITE3

hs = {
  "db_dir" => Arxutils::Dbutil::DB_DIR,
  "migrate_dir" => Arxutils::Dbutil::MIGRATE_DIR,
  "config_dir" => Arxutils::Dbutil::CONFIG_DIR,
  "dbconfig" => dbconfig,
  "log_fname" => Arxutils::Dbutil::DATABASELOG,
}

def print_diff( end_time , start_time )
  diff_time = end_time - start_time
  
  puts diff_time
  sec = (diff_time % 60.0).to_i
  total_min = (diff_time / 60.0).to_i
  min = total_min % 60
  total_hour = total_min / 60
  hour = total_hour % 24
  total_day = total_hour / 24
  puts %Q!#{total_day} Days #{hour} Hours #{min} minutes #{sec} seconds!
end
################################################
mode = :TRACE_MODE

time_hs = {}
puts Time.now

time_hs[:START] = Time.now

infname = ARGV[0]

mode = ARGV[1].to_sym if ARGV.size > 0
puts "mode=#{mode}"

pn = Pathname.new( infname )
basename = pn.basename(".*")
dirname = pn.dirname
ext = pn.extname
category_pn =  dirname + Pathname.new( basename.to_s + "_category" + ext.to_s )
chbk = Chbk::Chbk.new(
                      :db,
                      hs,
                      )
chbk.set_mode( mode )

def init(chbk , category_pn, pn )
  puts "load_category_file=#{category_pn}"
  chbk.load_category_file( category_pn )
  puts "load_bookmark_file=#{pn}"
  chbk.load_bookmark_file( pn )
end

def category_op(chbk, category_pn)
  puts "==list_category"
  chbk.list_category
end

def bookmark_op(chbk, pn)
  puts "call list_bookmark"
  chbk.list_bookmark
end


init(chbk, category_pn , pn )
time_hs[:CATEGORY_OP] = Time.now
category_op(chbk, category_pn)
time_hs[:ENSURE_CATEGORYHIER] = Time.now
chbk.ensure_categoryhier
time_hs[:BOOKMARK_OP] = Time.now
bookmark_op(chbk, pn)
time_hs[:ENSURE_INVALID] = Time.now

if mode == :TRACE_MODE
  puts "## ensure_invalid"
  chbk.ensure_invalid
end
chbk.ensure_management

time_hs[:END] = Time.now

################################################
puts ":START -> :END"
print_diff( time_hs[:END], time_hs[:START] )
puts "###"
puts ":START -> :CATEGORY_OP"
print_diff( time_hs[:CATEGORY_OP], time_hs[:START] )
puts "###"
puts ":CATEGORY_OP -> :ENSURE_CATEGORYHIER"
print_diff( time_hs[:CATEGORY_OP] , time_hs[:ENSURE_CATEGORYHIER] )

puts ":ENSURE_CATEGORYHIER -> :BOOKMARK_OP"
print_diff( time_hs[:BOOKMARK_OP] , time_hs[:ENSURE_CATEGORYHIER] )
puts "###"
puts ":BOOKMARK_OP -> :ENSURE_INVALID"
print_diff( time_hs[:ENSURE_INVALID] , time_hs[:BOOKMARK_OP]  )
puts "###"
puts ":ENSURE_INVALID -> :END"
print_diff( time_hs[:END] , time_hs[:ENSURE_INVALID] )
puts "###"
